import { getAvatarImage } from "./getAvatarImage";

export const avatarNames = [
  "avatar(1).jpg",
  "avatar(10).jpg",
  "avatar(11).jpg",
  "avatar(12).jpg",
  "avatar(13).jpg",
  "avatar(14).jpg",
  "avatar(15).jpg",
  "avatar(16).jpg",
  "avatar(17).jpg",
  "avatar(18).jpg",
  "avatar(19).jpg",
  "avatar(2).jpg",
  "avatar(20).jpg",
  "avatar(21).jpg",
  "avatar(22).jpg",
  "avatar(23).jpg",
  "avatar(24).jpg",
  "avatar(25).jpg",
  "avatar(26).jpg",
  "avatar(27).jpg",
  "avatar(28).jpg",
  "avatar(29).jpg",
  "avatar(3).jpg",
  "avatar(30).jpg",
  "avatar(31).jpg",
  "avatar(32).jpg",
  "avatar(33).jpg",
  "avatar(34).jpg",
  "avatar(35).jpg",
  "avatar(36).jpg",
  "avatar(37).jpg",
  "avatar(38).jpg",
  "avatar(39).jpg",
  "avatar(4).jpg",
  "avatar(40).jpg",
  "avatar(41).jpg",
  "avatar(42).jpg",
  "avatar(43).jpg",
  "avatar(44).jpg",
  "avatar(45).jpg",
  "avatar(46).jpg",
  "avatar(47).jpg",
  "avatar(48).jpg",
  "avatar(49).jpg",
  "avatar(5).jpg",
  "avatar(50).jpg",
  "avatar(51).jpg",
  "avatar(52).jpg",
  "avatar(53).jpg",
  "avatar(6).jpg",
  "avatar(7).jpg",
  "avatar(8).jpg",
  "avatar(9).jpg",
  "avatar.jpg",
];

export const getAllImages = () => {
  return avatarNames.map(name => getAvatarImage(name));
};
